### ISSUE TITLE
Grid layout space on the right on mobile version

### ISSUE THREAD

**Issue by stevebas16** [IliaDi/woocommerce-product-bundles-grid-layout-columns#1]
Hello,

It seems like there is a third columns on the grid layout on mobile version.
The content is not centered and there is a large gap on the right side (I can provide a screenshot if necessary).

Thanks

**Comment by IliaDi** [comment]
The mini-extension **does not** affect the number of columns in mobile view - it only works for Desktop. I double-checked to confirm this.

By default, bundled items appear in 1 column on mobile view, but you may be able to change that with some CSS. I recommend deactivating the mini-extension to check how the main Product Bundles works for you. If you have any issues, please reach out to plugin support by opening a ticket on WooCommerce.com. The large gap may be related to your active theme. I am testing with the Storefront theme on my site.
